# Site settings
title: Louis Sayer
logo: /files/profile picture reduced size.jpg
#author:
#  name: Evan Will
#  email: your-email@domain.com
#description: "Great site about Jekyll on GH-Pages."

# Build settings
theme: jekyll-theme-minimal
